export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'; //estar logeado
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UI_RESET_ERROR = 'UI_RESET_ERROR'; //borrar errores

export const AUTH_REMEMBER_PASSWORD_REQUEST = 'AUTH_REMEMBER_PASSWORD_REQUEST';
export const AUTH_REMEMBER_PASSWORD_SUCCESS = 'AUTH_REMEMBER_PASSWORD_SUCCESS';
export const AUTH_REMEMBER_PASSWORD_FAILURE = 'AUTH_REMEMBER_PASSWORD_FAILURE';

export const UI_SIGNUP_REQUEST = 'UI_SIGNUP_REQUEST';
export const UI_SIGNUP_SUCCESS = 'UI_SIGNUP_SUCCESS';
export const UI_SIGNUP_FAILURE = 'UI_SIGNUP_FAILURE';

export const UI_DELETE_USER_REQUEST = 'UI_DELETE_USER_REQUEST';
export const UI_DELETE_USER_SUCCESS = 'UI_DELETE_USER_SUCCESS';
export const UI_DELETE_USER_FAILURE = 'UI_DELETE_USER_FAILURE';

// Travels actions.types:

export const CREATE_TRAVEL_REQUEST = 'CREATE_TRAVEL_REQUEST';
export const CREATE_TRAVEL_SUCCESS = 'CREATE_TRAVEL_SUCCESS';
export const CREATE_TRAVEL_FAILURE = 'CREATE_TRAVEL_FAILURE';

export const DELETE_TRAVEL_REQUEST = 'DELETE_TRAVEL_REQUEST';
export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS';
export const DELETE_TRAVEL_FAILURE = 'DELETE_TRAVEL_FAILURE';

export const ADD_TRAVEL_REQUEST = 'ADD_TRAVEL_REQUEST';
export const ADD_TRAVEL_SUCCESS = 'ADD_TRAVEL_SUCCESS';
export const ADD_TRAVEL_FAILURE = 'ADD_TRAVEL_FAILURE';

export const FETCH_TRAVELS_REQUEST = 'FETCH_TRAVELS_REQUEST';
export const FETCH_TRAVELS_SUCCESS = 'FETCH_TRAVELS_SUCCESS';
export const FETCH_TRAVELS_FAILURE = 'FETCH_TRAVELS_FAILURE';
export const FILTER_TRAVELS_SUCCESS = 'FILTER_TRAVELS_SUCCESS';

export const EDIT_TRAVEL_REQUEST = 'EDIT_TRAVEL_REQUEST';
export const EDIT_TRAVEL_SUCCESS = 'EDIT_TRAVEL_SUCCESS';
export const EDIT_TRAVEL_FAILURE = 'EDIT_TRAVEL_FAILURE';

export const FETCH_SINGLE_TRAVEL_REQUEST = 'FETCH_SINGLE_TRAVEL_REQUEST';
export const FETCH_SINGLE_TRAVEL_SUCCESS = 'FETCH_SINGLE_TRAVEL_SUCCESS';
export const FETCH_SINGLE_TRAVEL_FAILURE = 'FETCH_SINGLE_TRAVEL_FAILURE';

export const BUY_TRAVEL_REQUEST = 'BUY_TRAVEL_REQUEST';
export const BUY_TRAVEL_SUCCESS = 'BUY_TRAVEL_SUCCESS';
export const BUY_TRAVEL_FAILURE = 'BUY_TRAVEL_FAILURE';

export const CLOSE_OPEN_TRAVEL_REQUEST = 'CLOSE_OPEN_TRAVEL_REQUEST';
export const CLOSE_OPEN_TRAVEL_SUCCESS = 'CLOSE_OPEN_TRAVEL_SUCCESS';
export const CLOSE_OPEN_TRAVEL_FAILURE = 'CLOSE_OPEN_TRAVEL_FAILURE';

// Locations actions.types:

export const FETCH_LOCATIONS_REQUEST = 'FETCH_LOCATIONS_REQUEST';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

// Delete only main travel photo:

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_FAILURE = 'DELETE_PHOTO_FAILURE';

//update user

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const AUTH_DETAIL_SUCCESS = 'AUTH_DETAIL_SUCCESS';

//Favorite
export const UPDATE_FAVORITE_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_FAVORITE_FAILURE = 'UPDATE_USER_FAILURE';
